name: BedwarsRandomJoin
version: 1.0.2
main: github.tsffish.bedwarsrandomjoin.BedwarsRandomJoin
author: tsffish
api-version: 1.13
commands:
  bwrj:
    description: Hello Command
    usage: /bwrj
  bwrj open:
    description: Open Command
    usage: /bwrj open
  bwrj join:
    description: Join Command
    usage: /bwrj join
  bwrj reload:
    description: Reload Command
    usage: /bwrj reload